package library_management.model;

/**
 * Book - Model / Domain Entity
 * 
 * Demonstrates OOP:
 * - Encapsulation: All fields are private, accessed through getters and setters.
 * - Constructors: Overloaded constructors for creating new books vs loading existing books from the DB.
 */
public class Book {

    private int bookId;
    private String title;
    private String author;
    private String category;
    private String isbn;
    private int publicationYear;
    private int totalQuantity;
    private int availableQuantity;

    // Default constructor
    public Book() {
    }

    // Constructor used when adding a NEW book (bookId is auto-generated by MySQL)
    public Book(String title, String author, String category, String isbn, int publicationYear, int totalQuantity, int availableQuantity) {
        this.title = title;
        this.author = author;
        this.category = category;
        this.isbn = isbn;
        this.publicationYear = publicationYear;
        this.totalQuantity = totalQuantity;
        this.availableQuantity = availableQuantity;
    }

    // Constructor used when retrieving an EXISTING book from the database
    public Book(int bookId, String title, String author, String category, String isbn, int publicationYear, int totalQuantity, int availableQuantity) {
        this.bookId = bookId;
        this.title = title;
        this.author = author;
        this.category = category;
        this.isbn = isbn;
        this.publicationYear = publicationYear;
        this.totalQuantity = totalQuantity;
        this.availableQuantity = availableQuantity;
    }

    // --- Getters and Setters (Encapsulation) ---

    public int getBookId() {
        return bookId;
    }

    public void setBookId(int bookId) {
        this.bookId = bookId;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getAuthor() {
        return author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public String getIsbn() {
        return isbn;
    }

    public void setIsbn(String isbn) {
        this.isbn = isbn;
    }

    public int getPublicationYear() {
        return publicationYear;
    }

    public void setPublicationYear(int publicationYear) {
        this.publicationYear = publicationYear;
    }

    public int getTotalQuantity() {
        return totalQuantity;
    }

    public void setTotalQuantity(int totalQuantity) {
        this.totalQuantity = totalQuantity;
    }

    public int getAvailableQuantity() {
        return availableQuantity;
    }

    public void setAvailableQuantity(int availableQuantity) {
        this.availableQuantity = availableQuantity;
    }

    @Override
    public String toString() {
        return String.format("Book [ID=%d, Title='%s', Author='%s', Category='%s', ISBN='%s', Year=%d, Total=%d, Available=%d]",
                bookId, title, author, category, isbn, publicationYear, totalQuantity, availableQuantity);
    }
}
